name: EcoPlugin
version: '${project.version}'
main: pl.ecocraft.ecoplugin.EcoPlugin
api-version: 1.18
website: https://kozminskihub.com/ecocraft/
commands:
  pollution:
    description: Check the current size of pollution.

  put-mask:
    description: Protect yourself from the polluted air by putting a mask.

  disasters:
    description: Display the list of current disasters.